import turtle
turtle.speed(8)
turtle.width(12)
turtle.color("blue")
turtle.circle(100)
turtle.up()
turtle.fd(220)
turtle.color("black")
turtle.down()
turtle.circle(100)
turtle.up()
turtle.color("red")
turtle.fd(220)
turtle.down()
turtle.circle(100)
turtle.up()
turtle.right(90)
turtle.fd(110)
turtle.right(90)
turtle.fd(100)
turtle.down()
turtle.color("green")
turtle.circle(-100)
turtle.up()
turtle.fd(220)
turtle.down()
turtle.color("yellow")
turtle.circle(-100)



